baseURL = '/'
languageCode = 'en-us'
title = 'GraphGuard | Precision Protection Systems'
relativeURLs = true

[params]
  tagline = "Professional Grade Protection"
  contact_email = "info@graphguard.ca"
